constants: # 커스텀 속성
  jwt:
    issuer: green502@green.com # JWT 토큰 발행자 정보
    bearer-format: JWT

    claim-key: signedUser
    secret-key: DeaguGreenArtAcademyClass502MsaCkassFighting # 비밀 레시피(절대 공개되어서는 안된다)

    access-token-cookie-name: access-token
    access-token-cookie-path: /
    access-token-cookie-validity-seconds: 900 #15분
    access-token-validity-milliseconds: 900_000 #15분

    refresh-token-cookie-name: refresh-token
    refresh-token-cookie-path: /api/user/reissue
    refresh-token-cookie-validity-seconds: 1_296_000 #15일
    refresh-token-validity-milliseconds: 1_296_000_000 #15일
  file:
    directory: /Users/soyoung/KDT/download/greengram

spring:
  application:
    name: greengram
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/greengram
    username: root
    password: qaws7579
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  servlet:
    multipart:
      max-file-size: 15MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml